# -*- coding: utf-8 -*-
"""Regex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1boYevl0GJ5GZqtTflR86uRMCIsx_jYNv
"""

import csv
import string
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

DATAPATH = '/content/drive/MyDrive/Data/'

news_dataset = pd.read_csv(DATAPATH+'Dataset.csv')
edition_dataset = pd.read_csv(DATAPATH+'campaigns.csv')

edition_dataset['plain_text'][147]

randombullshit = [
                  'Selamat pagi [Name]!',
                  'Selamat hari Senin, [Name]!',
                  'Selamat hari Selasa, [Name]!',
                  'Selamat hari Rabu, [Name]!',
                  'Selamat hari Kamis, [Name]!',
                  'Selamat hari Jumat, [Name]!',
                  'Selamat hari Sabtu, [Name]!',
                  'Selamat hari Minggu, [Name]!',
                  'SELAMAT HARI RAYA IDUL FITRI 1443H'

]

for x in range(len(edition_dataset)):
  edition_dataset['plain_text'][x] = edition_dataset['plain_text'][x].replace('\n',' ')
  edition_dataset['plain_text'][x] = edition_dataset['plain_text'][x].replace('\r','')
  for y in randombullshit:
    edition_dataset['plain_text'][x] = edition_dataset['plain_text'][x].replace(y,'')

edition_dataset['plain_text'][2]

import re
re.findall("(?<=2021|2022)(.*)(?=Catatan)", edition_dataset['plain_text'][2])

